prefix = "BCD"
vnet_name = "COVID-IaaSVNet"
vnet_rg = "canadastats-common"
subnet_cidr_public = "10.0.0.192/26"
subnet_cidr_private = "10.0.1.0/26"
check_secret_scopes_url = "https://terraformlabcanadastats.blob.core.windows.net/notebooks/Check Secret Scopes.py"