name: Steps 1-3 - Terraform Plan
on:
  workflow_dispatch:
    inputs:
      prefix:
        description: '3 letter Prefix'     
        required: true
        default: 'ABC'
      logLevel:
        description: 'Log level'     
        required: false
        default: 'warning'

jobs:
  terraform:
    #runs-on: self-hosted
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: 6fb69fe3-eba6-4e96-9546-b6399a1a0af5
      ARM_CLIENT_SECRET: ${{secrets.TF_ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: b464a5af-90a6-414d-b676-cd2f9fa3a5a4
      ARM_TENANT_ID: 05fc097a-05d5-48a8-8ad7-44221fa2d524

    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        working-directory: Steps1-3

      - name: Terraform Format
        run: terraform fmt -check
        working-directory: Steps1-3

      - name: Terraform Plan
        run: terraform plan -var prefix="${{ github.event.inputs.prefix }}" -client_id=${ARM_CLIENT_ID} -client_secret=${ARM_CLIENT_SECRET} -tenant_id=${ARM_TENANT_ID}
        working-directory: Steps1-3